# Define the order of the groups
group.default_view:
  order: 1
group.climate:
  order: 2
group.security:
  order: 3
group.system_monitor:
  order: 4

#alarm_control_panel.1545_base_station:
#  friendly_name: 1545 Base Station
#  icon: mdi:security
#sun.sun:
#  icon: mdi:sun
#device_tracker.daves_iphone:
#  friendly_name: Dave