############################################################
#
# Home Assistant - Device Trackers
#
############################################################

- platform: tomato
  host: !secret tomato_host
  port: !secret tomato_port
  username: !secret tomato_username 
  password: !secret tomato_password 
  http_id: !secret tomato_http_id
  track_new_devices: no