####################################################
#                                                  #
#                   HA Service            #
#                                                  #
####################################################

homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: !secret home_ele
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
http:
  api_password: !secret http_password
  trusted_networks:
    - 127.0.0.1
  ip_ban_enabled: true
  login_attempts_threshold: 5
  base_url: !secret http_url
  use_x_forwarded_for: true

####################################################
#                                                  #
#                     Enables             #
#                                                  #
####################################################

config:
conversation:
discovery:
frontend:
  javascript_version: latest
history:
  exclude:
    domains:
      - automation
      - weblink
      - media_player
  include:
    domains:
      - sensor
      - binary_sensor
      - switch
      - climate
ios:
logbook:
map:
sun:
  elevation: 2

####################################################
#                                                  #
#                    Components            #
#                                                  #
####################################################

alarm_control_panel:
  - platform: arlo

arlo:
  username: !secret arlo_username
  password: !secret arlo_password

google:
  client_id: !secret google_api_client_id
  client_secret: !secret google_api_client_secret

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

tts:
  - platform: google
  
####################################################
#                                                  #
#                     Includes             #
#                                                  #
####################################################

device_tracker: !include includes/device_trackers.yaml
camera: !include includes/cameras.yaml
group: !include_dir_merge_named includes/groups
sensor: !include includes/sensors.yaml
zone: !include includes/zones.yaml