############################################################
#
# Home Assistant - Groups - 1545 House
#
############################################################

house:
  view: yes
  icon: mdi:home
  entities:
    - group.1545_climate
    - group.489_climate
    - group.trackeddevices

1545_climate:
  name: 1545 Climate
  view: no
  entities:
    - sensor.north_nest_thermostat_temperature
    - sensor.south_nest_thermostat_temperature
    - sensor.north_nest_thermostat_humidity
    - sensor.south_nest_thermostat_humidity
    - climate.north_nest
    - climate.south_nest

489_climate:
  name: 489 Climate
  view: no
  entities:
    - sensor.kingsbridge_thermostat_temperature
    - sensor.kingsbridge_thermostat_humidity
    - climate.kingsbridge

trackeddevices:
  name: Devices
  view: no
  entities:
    - device_tracker.daves_iphone