############################################################
#
# Home Assistant - Groups - 1545 House
#
############################################################

house:
  view: yes
  icon: mdi:home
  entities:
    - group.trackeddevices

trackeddevices:
  name: Devices
  view: no
  entities:
    - device_tracker.daves_iphone