############################################################
#
# Home Assistant - Groups - Default View
#
############################################################

default_view:
  view: yes
  icon: mdi:home-assistant
  entities:
    - device_tracker.daves_iphone
    - group.zulu_time
zulu_time:
  name: Zulu Time
  view: no
  entities:
    - sensor.zulu_time