############################################################
#
# Home Assistant - Groups - Security
#
############################################################

security:
  view: yes
  icon: mdi:cctv
  entities:
    - group.cameras
cameras:
  name: Cameras
  view: no
  entities:
    - alarm_control_panel.1545_base_station
    - camera.front_door
    - camera.pool
    - camera.dogcam
    - camera.park
    - camera.garage
