############################################################
#
# Home Assistant - Groups - System Monitor
#
############################################################

system_monitor:
  view: yes
  icon: mdi:server-network
  entities:
    - group.ha
    - group.wan_health
ha:
  name: Home Assistant
  view: no
  entities:
    - sensor.ha_uptime
    - sensor.ha_db_size

wan_health:
  name: WAN Health
  view: no
  entities:
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.speedtest_ping