############################################################
#
# Home Assistant - Groups - System Monitor
#
############################################################

system_monitor:
  view: yes
  icon: mdi:server-network
  entities:
    - group.system
system:
  name: System
  view: no
  entities:
    - sensor.ha_uptime
    - sensor.speedtest_download
    - sensor.speedtest_upload
    - sensor.speedtest_ping
    - sensor.ha_db_size